/* Copyright 2022 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"

#define XXX KC_NO

#define LAYOUT( \
    K00, K01, K02, K03, K04, K05, K06, K46, K45, K44, K43, K42, K47, K48, \
    K10, K11, K12, K13, K14, K15, K16, K56, K55, K54, K53, K52, K57, K58, \
    K20, K21, K22, K23, K24, K25, K26, K66, K65, K64, K63, K62, K68, \
    K30, K32, K33, K34, K35, K36, K76, K75, K74, K73, K72, K78, \
    K80, K81, K82, K86, K84, K83, K87, K88  \
) { \
    { K00, K01, K02, K03, K04, K05, K06, XXX, XXX }, \
    { K10, K11, K12, K13, K14, K15, K16, XXX, XXX }, \
    { K20, K21, K22, K23, K24, K25, K26, XXX, XXX }, \
    { K30, XXX, K32, K33, K34, K35, K36, XXX, XXX }, \
    { XXX, XXX, K42, K43, K44, K45, K46, K47, K48 }, \
    { XXX, XXX, K52, K53, K54, K55, K56, K57, K58 }, \
    { XXX, XXX, K62, K63, K64, K65, K66, XXX, K68 }, \
    { XXX, XXX, K72, K73, K74, K75, K76, XXX, K78 }, \
    { K80, K81, K82, K83, K84, XXX, K86, K87, K88 }, \
}

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/
